# Generated by Django 3.2.19 on 2023-05-23 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0003_alter_ingredientinrecipe_ingredient'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopCart',
            new_name='Cart',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='shopcart_unique',
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients', verbose_name='Ингредиент'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='cart_unique'),
        ),
    ]
